name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          8.0.x

    - name: Restore dependencies
      run: dotnet restore Intar.Tests/Intar.Tests.csproj

    - name: Test
      run: dotnet test Intar.Tests/Intar.Tests.csproj --configuration Release --no-restore
